apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: agroscrapper
type: Opaque
stringData:
  telegram-token: "your_bot_token_here"
  telegram-chatid: "your_chat_id_here"
  telegram-threadid: "your_thread_id_here"
